### ISSUE TITLE
Use confd for configuration

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/stack-play#4]
Use confd-configuration files for configuration,

Override: /etc/confd/confd.toml
```toml
confdir = "/etc/confd"
backend = "file"
file = [ "/etc/confd/horizon-config.yaml" ]
log-level = "debug"
```
